# Site settings
title: "kfwong"
email: kfwong@zoho.com
description: "kfwong's scrapbook & dev journal"
baseurl: 
url: "http://kfwong.github.io/"
title_description: "Yet another tech blog to share my learning journey! I'll try my best to update as often as I could! Hopefully..."
title_image: "http://www.gravatar.com/avatar/0241ee41f391dccfd9b9b8da3f45d624?s=500&d=mm"
google_analytics: ""
disqus_account: whitekoffee
github_repository: https://github.com/kfwong/kfwong.github.io
addthis_id: 
post_limit: 10

# Social usernames/URLs
twitter_username: 
github_username:  kfwong
linkedin_link: 
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
