name: kfwong's lovely dev journal
description: 
markdown: redcarpet
highlighter: pygments
paginate: 10
intro: A personal tech blog to dump my crappy notes... and stuff I find them interesting to share!
logo: logo.png
disqus_shortname:

# Owner/author information
owner:
  name:           kfwong
  avatar:         <avatar-image-link>
  email:          kfwong@zoho.com
  github: https://github.com/kfwong
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Links to include in top navigation
# For external links add external: true
