name: White Paper
markdown: redcarpet
highlighter: pygments
url: http://0.0.0.0:4000/
paginate: 10
description: Jekyll theme for Programmers
intro: White Paper is a Jekyll theme most suited to be used on tech blogs that like their content to shine.
logo: logo.png
disqus_shortname:

# Owner/author information
owner:
  name:           kfwong
  avatar:         <avatar-image-link>
  email:          kfwong@zoho.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github: https://github.com/kfwong
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
bing_verify:

# Links to include in top navigation
# For external links add external: true
